# -*- coding: utf-8 -*-
"""mang1chieu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WvlnGEkKBxhKUstafqZltJFljSSZcDf_
"""

# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""
import numpy as np

#Các phép toán vpới ma trận
#x = np.array([[1,2,3],[2,5,3]])
#y = np.array([[1,3,2],[5,2,1]])             
             
#Cộng 2 ma trận,  cộng tưng phần tử tương ứng với nhau
#s = x + y
#print("Tổng hai ma trận: \n", s)
#print("Tổng hai ma trận: \n", np.add(x,y))
             
from numpy import random 

#Tạo mảng 1 chiều, n nhập từ bàn phím, giá trị khởi tọa ngẫu nhiên trong khoảng [1,50]
try:
    n = int(input("Nhập số phần tử n: "))
    if n <= 0:
        print('Phải nhập lớn hơn 0!')
        exit()
except:
    print('Phải nhập số nguyên!')
    exit()

a = []

for i in range(n):
    a = random.randint(1,51, size =(n))
print('Mảng: ', a)

#Tổng giá trị mảng
tong = sum(a)
print('Tổng mảng: ', tong)

#Giá trị lớn nhất mảng
soMax = max(a)
print('Số lớn nhất trong mảng là: ', soMax)

#Giá trị nhỏ nhất mảng
soMin = min(a)
print('Số nhỏ nhất trong mảng là: ', soMin)

#Giá trị trung bình mảng
tb = a.mean()
print('Giá trị trung bình của mảng là: ', tb)
           

#Thêm 1 phần tử x vào cuối mảng
#x  = int(input('Giá trị phần tử x: '))
#a.append(x)

#Xoá 1 phần tử y trong mảng
#y  = int(input('Giá trị phần tử y: '))

#Sắp xếp mảng tăng dần
for i in range(0, n - 1):
    for j in range(i + 1, n):
        if (a[i] > a[j]):
            # Hoán đổi vị trí
            tmp = a[i]
            a[i] = a[j]
            a[j] = tmp
print('Mảng sau khi sắp xếp tăng dần: ', a)
#Tạo mảng chứa tất cả các số lẻ trong mảng và sắp giảm dần
x = np.array([3,7,11,1,9,15,25])
print('Mảng trước khi sắp xếp: ', x)
x1 = len(x)
for i in range(0, x1 - 1):
    for j in range(i + 1, x1):
        if (x[i] < x[j]):
            # Hoán đổi vị trí
            tmp = x[i]
            x[i] = x[j]
            x[j] = tmp
print('Mảng sau khi sắp xếp giảm dần: ', x)